server:
  port: 8081
  error:
    include-message: never
  servlet:
      context-path: /api 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: PRODUCT-SERVICE
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 2905
  elasticsearch:
    uris: http://localhost:9200
    password: changeme
    username: elastic
    connection-timeout: 5s


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: false
        format_sql: true
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        size-parameter: size
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
      sort:
        sort-parameter: sort

  profiles:
    active: dev

  sql:
    init:
      mode: always
